version: '3'

services:
  postgres:
    container_name: pg-${POSTGRES_IMAGE_VERSION_TAG:-latest}
    image: postgres:${POSTGRES_IMAGE_VERSION_TAG:-latest}
    env_file:
      - .env
    ports:
      - ${EXPOSE_POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
 
  pgadmin:
    container_name: pg-admin-web-4
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - ${EXPOSE_PG_ADMIN_PORT}:80
    volumes:
      - ./data/pg-admin:/var/lib/pgadmin
